apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-backend
  namespace: aura
  labels:
    app: aura-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aura-backend
  template:
    metadata:
      labels:
        app: aura-backend
    spec:
      containers:
        - name: backend
          image: bittush8789/aura-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: GROQ_LLM_MODEL
              valueFrom:
                configMapKeyRef:
                  name: aura-config
                  key: GROQ_LLM_MODEL
            - name: GROQ_WHISPER_MODEL
              valueFrom:
                configMapKeyRef:
                  name: aura-config
                  key: GROQ_WHISPER_MODEL
            - name: CHROMA_DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: aura-config
                  key: CHROMA_DB_PATH
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aura-secrets
                  key: GROQ_API_KEY
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: aura-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: aura-secrets
                  key: EMAIL_PASS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aura-secrets
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: chroma-volume
              mountPath: /app/chroma_db
      volumes:
        - name: chroma-volume
          persistentVolumeClaim:
            claimName: chroma-pvc
